JWT 및 OAuth 2.0을 통한 로그인 기능 구현
epark-grace/devspace pull request #9
Opened 2022-07-19 10:00 UTC by destitutor

# 설명
JWT 및 OAuth 2.0을 통해서 깃허브와 구글 계정을 통한 로그인을 지원합니다. 구체적인 동작은 [노션](https://www.notion.so/JWT-OAuth-2-0-6aae54ddd17a4958a7c93e0d43b774d8)에서 확인할 수 있습니다.

## 변경 유형
- [x] 호환성을 깨뜨리는 변경 (기존 기능이 기대하는 대로 작동하지 않을 수 있는 수정 혹은 기능)
- [x] 이 변경 내역을 적용하려면 문서를 업데이트해야 함

2022-07-19 10:22 UTC, destitutor commented on backend/src/main/java/our/portfolio/devspace/configuration/WebSecurityConfiguration.java
> +        configuration.setAllowCredentials(true);
이 부분은 우선은 편의상 와일드카드로 설정해 두었습니다. 향후에 허용할 출처 목록으로 수정해주시면 감사하겠습니다 😄

2022-07-20 14:40 UTC, epark-grace requested changes
리뷰가 너무 늦었어요. 죄송합니다. 고생 많으셨습니다!👍

2022-07-20 14:40 UTC, epark-grace commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/handler/OAuth2AuthenticationFailureHandler.java
> +            .orElse(("/"));
OAuth 로그인 실패시 port 8080의 서버 "/" 경로로 리다이렉트 됩니다. port 80의 클라이언트 "/" 경로로 리다이렉트 되도록 변경하는게 좋지 않을까요?

2022-07-20 14:40 UTC, epark-grace commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        if(redirectUri.isPresent()) {
로그인 요청 URL에 리다이렉트 URI가 있으면 예외 발생합니다. 수정이 필요할 것 같습니다.

2022-07-20 14:40 UTC, epark-grace commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        return redirectUri.orElse(getDefaultTargetUrl());
스프링 설정상 DefaultTargetUrl는 서버포트 8080의 "/" 이기 때문에 redirect url 없이 접근할 경우 token을 서버 포트로 넘겨줍니다. 디폴트 url이나 orElse 파라미터를 클라이언트 포트 url로 변경하는 게 좋을 것 같습니다.

2022-07-20 14:40 UTC, epark-grace commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
> +            CookieUtils.deleteCookie(request, response, OAUTH2_AUTHORIZATION_REQUEST_COOKIE_NAME);
아래에 정의한 removeAuthorizationRequestCookies 메서드 내용과 동일해서 메서드 호출로 대체할 수 있을 것 같습니다.

2022-07-20 14:40 UTC, epark-grace commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/userinfo/GithubOAuth2UserInfo.java
> +        return (String) attributes.get("email");
사용자의 깃허브 계정에 email이 비공개 설정되어 있는 경우 email attribute가 null이 되는 문제가 있습니다.  devspace는 이메일로 사용자를 구분하기 때문에 email이 꼭 필요한데 다른 방법으로 email을 받아와야 할 것 같아요. 다행히 방법이 아주 없진 않아서 일단 당장 수정은 미뤄두고 따로 논의해서 처리하는게 어떨까요?
참고: [Github user email is null, despite user:email scope](https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope)

2022-07-21 01:41 UTC, destitutor commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
> +            CookieUtils.deleteCookie(request, response, OAUTH2_AUTHORIZATION_REQUEST_COOKIE_NAME);
수정했습니다. 감사합니다 😄

2022-07-21 01:48 UTC, destitutor commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        if(redirectUri.isPresent()) {
아, 이 부분은 제가 인가되지 않은 경로로 리다이렉트 시키는 것을 허가하지 않는 코드를 지워버려서 항상 저 조건문에 걸리는 것 같네요. 빠른 시일 내로 수정하도록 하겠습니다.

```java
// 쿠키에 리다이렉트 경로(redirect_uri)가 지정되어 있고 해당 경로가 인가된 경로인 경우에만 허용한다.
if(redirectUri.isPresent() && !isAuthorizedRedirectUri(redirectUri.get())) {
  throw new IllegalArgumentException("Sorry! We've got an Unauthorized Redirect URI and can't proceed with the authentication");
}
```

2022-07-21 01:52 UTC, destitutor commented on backend/src/main/java/our/portfolio/devspace/configuration/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        return redirectUri.orElse(getDefaultTargetUrl());
이것 역시 설정 파일에 별도로 기본 경로를 작성하고 가져올 수 있도록 하겠습니다. 감사합니다 😄

2022-07-21 22:27 UTC, merged